version: '3.9'

services:
  db:
    image: "${ORACLE_RELEASE_NAME}:${ORACLE_RELEASE_VERSION}"
    container_name: ${ORACLE_CONTAINER}
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      # ORACLE_RANDOM_PASSWORD: true
      ORACLE_DATABASE: ${ORACLE_DATABASE}
      APP_USER: ${ORACLE_APP_USER}
      APP_USER_PASSWORD: ${ORACLE_APP_USER_PASSWORD}
    ports:
      - ${ORACLE_PORT}:80
    volumes:
      - db-data:/opt/oracle/oradata
    networks:
      - net
    # Provide healthcheck script options for startup
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 5s

volumes:
  db-data:
    driver: local

networks:
  net:
    driver: bridge
